// @ts-check

module.exports = {
  docsSidebar: [
    {
      type: "category",
      key: "conholdate-total-java",
      label: "Conholdate.Total for Java",
      collapsible: false,
      items: [
        {
          type: "category",
          key: "product-viewer",
          label: "Viewer v26.5",
          items: [
            {
              type: "autogenerated",
              dirName: "viewer"
            }
          ]
        }
      ]
    }
  ]
};
