// @ts-check

module.exports = {
  docsSidebar: [
    {
      type: "category",
      key: "conholdate-total-net",
      label: "Conholdate.Total for .NET",
      collapsible: false,
      items: [
        {
          type: "category",
          key: "product-annotation",
          label: "Annotation v26.6.0",
          items: [
            {
              type: "autogenerated",
              dirName: "annotation"
            }
          ]
        },
        {
          type: "category",
          key: "product-assembly",
          label: "Assembly v26.7.0",
          items: [
            {
              type: "autogenerated",
              dirName: "assembly"
            }
          ]
        },
        {
          type: "category",
          key: "product-comparison",
          label: "Comparison v26.8.0",
          items: [
            {
              type: "autogenerated",
              dirName: "comparison"
            }
          ]
        },
        {
          type: "category",
          key: "product-conversion",
          label: "Conversion v26.8.0",
          items: [
            {
              type: "autogenerated",
              dirName: "conversion"
            }
          ]
        },
        {
          type: "category",
          key: "product-editor",
          label: "Editor v26.6.1",
          items: [
            {
              type: "autogenerated",
              dirName: "editor"
            }
          ]
        },
        {
          type: "category",
          key: "product-markdown",
          label: "Markdown v26.3.0",
          items: [
            {
              type: "autogenerated",
              dirName: "markdown"
            }
          ]
        },
        {
          type: "category",
          key: "product-merger",
          label: "Merger v26.7.0",
          items: [
            {
              type: "autogenerated",
              dirName: "merger"
            }
          ]
        },
        {
          type: "category",
          key: "product-metadata",
          label: "Metadata v26.8.0",
          items: [
            {
              type: "autogenerated",
              dirName: "metadata"
            }
          ]
        },
        {
          type: "category",
          key: "product-parser",
          label: "Parser v26.8.0",
          items: [
            {
              type: "autogenerated",
              dirName: "parser"
            }
          ]
        },
        {
          type: "category",
          key: "product-redaction",
          label: "Redaction v26.7.0",
          items: [
            {
              type: "autogenerated",
              dirName: "redaction"
            }
          ]
        },
        {
          type: "category",
          key: "product-search",
          label: "Search v26.8.0",
          items: [
            {
              type: "autogenerated",
              dirName: "search"
            }
          ]
        },
        {
          type: "category",
          key: "product-signature",
          label: "Signature v26.6.0",
          items: [
            {
              type: "autogenerated",
              dirName: "signature"
            }
          ]
        },
        {
          type: "category",
          key: "product-viewer",
          label: "Viewer v26.4.0",
          items: [
            {
              type: "autogenerated",
              dirName: "viewer"
            }
          ]
        },
        {
          type: "category",
          key: "product-watermark",
          label: "Watermark v26.9.0",
          items: [
            {
              type: "autogenerated",
              dirName: "watermark"
            }
          ]
        }
      ]
    }
  ]
};
