// @ts-check

module.exports = {
  docsSidebar: [
    {
      type: "category",
      label: "Conholdate.Total for .NET",
      collapsible: false,
      items: [
        {
          type: "category",
          label: "Viewer v26.5",
          items: [
            {
              type: "autogenerated",
              dirName: "total/net/viewer/v26.5"
            }
          ]
        }
      ]
    }
  ]
};
