// @ts-check

module.exports = {
  docsSidebar: [
    {
      type: "category",
      key: "conholdate-total-net",
      label: "Conholdate.Total for .NET",
      collapsible: false,
      items: [
        {
          type: "category",
          key: "product-conversion",
          label: "Conversion v26.7.0",
          items: [
            {
              type: "autogenerated",
              dirName: "conversion"
            }
          ]
        },
        {
          type: "category",
          key: "product-metadata",
          label: "Metadata v26.8.0",
          items: [
            {
              type: "autogenerated",
              dirName: "metadata"
            }
          ]
        },
        {
          type: "category",
          key: "product-viewer",
          label: "Viewer v26.4.0",
          items: [
            {
              type: "autogenerated",
              dirName: "viewer"
            }
          ]
        }
      ]
    }
  ]
};
