// @ts-check

module.exports = {
  docsSidebar: [
    {
      type: "category",
      label: "Conholdate.Total for .NET",
      collapsible: false,
      items: [
        {
          type: "category",
          label: "Viewer v26.4.0",
          items: [
            {
              type: "autogenerated",
              dirName: "total/net/viewer/v26.4.0"
            }
          ]
        },
        {
          type: "category",
          label: "Conversion v26.7.0",
          items: [
            {
              type: "autogenerated",
              dirName: "total/net/conversion/v26.7.0"
            }
          ]
        }
      ]
    }
  ]
};
